[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_src_filter = +<main.cpp>
lib_deps =
    waspinator/AccelStepper@^1.61
    tzapu/WiFiManager@^2.0.17
    dfrobot/DFRobotDFPlayerMini@^1.0.6

[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_src_filter = +<nano/*>
lib_deps =
    waspinator/AccelStepper@^1.61

